//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.94")]
        public double A {
            get {
                return ((double)(this["A"]));
            }
            set {
                this["A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.91")]
        public double B {
            get {
                return ((double)(this["B"]));
            }
            set {
                this["B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KierownikProjektu {
            get {
                return ((string)(this["KierownikProjektu"]));
            }
            set {
                this["KierownikProjektu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Szacujacy {
            get {
                return ((string)(this["Szacujacy"]));
            }
            set {
                this["Szacujacy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NazwaFirmy {
            get {
                return ((string)(this["NazwaFirmy"]));
            }
            set {
                this["NazwaFirmy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Adres {
            get {
                return ((string)(this["Adres"]));
            }
            set {
                this["Adres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Telefon {
            get {
                return ((string)(this["Telefon"]));
            }
            set {
                this["Telefon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Email {
            get {
                return ((string)(this["Email"]));
            }
            set {
                this["Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double StawkaGodz {
            get {
                return ((double)(this["StawkaGodz"]));
            }
            set {
                this["StawkaGodz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("152")]
        public long OsoboMGodz {
            get {
                return ((long)(this["OsoboMGodz"]));
            }
            set {
                this["OsoboMGodz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public long DzRobGodz {
            get {
                return ((long)(this["DzRobGodz"]));
            }
            set {
                this["DzRobGodz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int JezykProgramowania {
            get {
                return ((int)(this["JezykProgramowania"]));
            }
            set {
                this["JezykProgramowania"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.27")]
        public double UUCPnaUFP {
            get {
                return ((double)(this["UUCPnaUFP"]));
            }
            set {
                this["UUCPnaUFP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.67")]
        public double C {
            get {
                return ((double)(this["C"]));
            }
            set {
                this["C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.28")]
        public double D {
            get {
                return ((double)(this["D"]));
            }
            set {
                this["D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfInt xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <int>18</int>
  <int>54</int>
  <int>98</int>
  <int>14</int>
  <int>99</int>
  <int>53</int>
  <int>59</int>
  <int>55</int>
  <int>42</int>
  <int>18</int>
  <int>24</int>
  <int>65</int>
  <int>191</int>
  <int>45</int>
  <int>35</int>
  <int>40</int>
  <int>49</int>
  <int>53</int>
  <int>53</int>
  <int>48</int>
  <int>30</int>
  <int>21</int>
  <int>34</int>
  <int>60</int>
  <int>40</int>
  <int>32</int>
  <int>15</int>
  <int>80</int>
  <int>35</int>
  <int>28</int>
  <int>80</int>
  <int>66</int>
  <int>37</int>
  <int>60</int>
  <int>75</int>
  <int>21</int>
  <int>60</int>
  <int>44</int>
</ArrayOfInt>")]
        public int[] TabPrzeliczeniowa {
            get {
                return ((int[])(this["TabPrzeliczeniowa"]));
            }
            set {
                this["TabPrzeliczeniowa"] = value;
            }
        }
    }
}
